// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Match Next.js env precedence so the Prisma CLI uses the same connection the
// app does: .env.local wins over .env, and anything already in the real
// environment (e.g. Vercel) wins over both. dotenv never overrides a var that
// is already set, so loading .env.local first makes its values take priority.
loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer the direct (unpooled) connection for CLI DDL like `db push` /
    // migrations; fall back to the pooled URL when there's no separate one.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
